
            <?php
            $form = $this->form;
            $form->setAttribute('class', 'form-horizontal');
            $form->prepare();
//$form->setAttribute('action', $this->url('application', array('action' => 'edit')))->prepare();
            echo $this->form()->openTag($form);
            ?>


            <?php $multiplo = 2; ?>
            <?php $countRow = 2; ?>
            <?php foreach ($form as $element) : ?>

                <?php switch ($element->getAttribute('type')): ?>
<?php case "hidden": ?>
                        <?php echo $this->formElement($element); ?>
                        <?php break; ?>
                    <?php
                    case "submit" :
                    case "button" :
                        ?>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-xs-12 ">
                                <div  class="form-group">
                                    <div class="col-lg-12 col-md-12 col-xs-12 ">
                                        <?php echo $this->formElement($element); ?>     
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php
                        break;

                    default:
                        ?>

                        <?php
                        $element->setAttribute('class', 'form-control');
                        ?>
                        <div class="row">


                            <div class="col-lg-12 col-md-12 col-xs-12">
                                <?php echo $this->partial('cdi-commons/form/element/placeholder', array('element' => $element)); ?>
                            </div>

                        </div>


                        <?php break; ?>
                <?php endswitch; ?>

            <?php endforeach; ?>

            <?php echo $this->form()->closeTag($form); ?>
