<div class='modal fade' id='cdiModal'>
    <div class='modal-dialog modal-lg'>
        <div class='modal-content'>
            <div class='modal-header'>
                <button type='button' class='close' data-dismiss='modal'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button>
                <h4 class='modal-title'><div id='cdiTitle'>-</div></h4>
            </div>
            <div class='modal-body'>
                <div id='cdiAjaxContent'></div>
            </div>
        </div>
    </div>
</div>
